### ISSUE TITLE
Spotify Controls plugin broken

### ISSUE THREAD

**Issue by willbert03** [maenDisease/Float#2]
The [Spotify controls plugin ](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/SpotifyControls)breaks with this theme. You could probably embed it into the server pannel and just show the album cover - then clicking the album opens up the normal menu. 
Hovered
![image](https://user-images.githubusercontent.com/71606954/154696022-87c1b79a-683f-41c5-85ce-04c686016ad4.png) 
Not hovered
![image](https://user-images.githubusercontent.com/71606954/154696059-2da2face-0f80-4b95-8bff-ad26caf1e11c.png)

**Comment by maenDisease** [comment]
That's by design, probably not possible to put the player in the channel drawer without reverting the user panel
