### ISSUE TITLE
Giant grey area

### ISSUE THREAD

**Issue by mglass99** [maenDisease/Float#4]
![b3b615c3e2dbe63a702903d26e26f468](https://github.com/user-attachments/assets/e0249514-c5aa-4f77-96e7-e013fd9ac0e5)

**Comment by Sh1nchaan** [comment]
They found workarounds on discord

**Comment by mglass99** [comment]
The following is the fix that was posted to Discord. 

> press ctrl+shift+i and it should open the console up
> click the little arrows until you get to the "<div data-collapsed="false" class="sidebar_a4d4d9">" bar, type in "html" in the filters bar to find the code thats in the screenshot from before, then just unclick the checkmark at "width"

https://github.com/user-attachments/assets/5c188e59-e696-477c-b36f-acc846c8ea8b
